### ISSUE TITLE
Cannot install in Laravel 5.3

### ISSUE THREAD

**Issue by ulshamim** [ksungcaya/phpass-laravel#4]
I can not install this package in L5.3.

**Comment by ksungcaya** [comment]
Sorry couldn't update the repository but for the mean time, what you could do is fork the master and update your composer.json and composer.lock files. I'll update the repository as soon as I'm free.

**Comment by ksungcaya** [comment]
@ulshamim I've updated the package to [v1.2](https://github.com/ksungcaya/phpass-laravel/releases/tag/1.2). Apologies for being late. 😅
